#ifndef BUTTON_H
#define BUTTON_H

#define BUTTON_GPIO MXC_GPIO0
#define BUTTON_IRQn GPIO0_IRQn
#define BUTTON_BTNR_PIN MXC_GPIO_PIN_22
#define BUTTON_BTNL_PIN MXC_GPIO_PIN_21
#define BUTTON_BTNM_PIN MXC_GPIO_PIN_25
#define BUTTON_TIMER_TICK_EVENT 0xFC

enum {
    BUTTON_BTNR_NO,
    BUTTON_BTNL_NO,
    BUTTON_BTNM_NO,
    BUTTON_COUNT
};

void Button_Init();

#endif